# Generated by Django 5.2 on 2025-04-12 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookrelation',
            old_name='Book',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='userbookrelation',
            unique_together={('user', 'book')},
        ),
    ]
