# Generated by Django 5.2 on 2025-04-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_book_userbookrelation_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='shelf',
            field=models.CharField(choices=[('WANT_TO_READ', 'Want to Read'), ('READING', 'Currently Reading'), ('READ', 'Finished'), ('FAVOUTITE', 'Favourite')], default='WANT_TO_READ', max_length=20),
        ),
    ]
